### ISSUE TITLE
[Help needed] Run without Docker

### ISSUE THREAD

**Issue by prabapro** [Nikeev/sesdashboard#2]
Hi,

Can this be used as a standalone app without Docker? (I'm using Lamp stack)

Thanks

**Comment by Nikeev** [comment]
Hello!

Yes, it can be used without Docker. 

Your Apache configuration should use **public/** folder as web root. For more details about Apache configuring and .htaccess examples you could find here: https://symfony.com/doc/current/setup/web_server_configuration.html

For database setup just fill **DATABASE_URL=** in _.env.local_ with your database credentials.

When it's done, you should run composer install, run migrations and create admin user.

**Comment by prabapro** [comment]
Hi @Nikeev ,

Thank you so much. Appreciate it.

**Comment by MaximilianKohler** [comment]
I'm not quite clear on the directions. For running without docker, it seems that we use the Shared Hosting https://sesdashboard.readthedocs.io/en/latest/install.html instructions.

I'm using centmin mod, and it installs a vhost to `/home/nginx/domains/sesdashboard.mysite.com/`. In that folder is a `public`, `private`, `log`, `backup`. 

We cd to `/home/nginx/domains/sesdashboard.mysite.com/public` and then run `Git clone https://github.com/Nikeev/sesdashboard.git` or upload the source code .zip https://github.com/Nikeev/sesdashboard/releases so that it's `/home/nginx/domains/sesdashboard.mysite.com/public/sesdashboard`?

The installation docs say `so your webserver should use /public/index.php` and my `/home/nginx/domains/sesdashboard.mysite.com/public/` doesn't have a `index.php`. It only has .html files. I saw a `index.php` file in `/home/nginx/domains/sesdashboard.mysite.com/public/sesdashboard/public` so am I supposed to be copying the contents of `sesdashboard/public` to `/home/nginx/domains/sesdashboard.mysite.com/public/`? That doesn't seem to be correct based on the other files & folders I'm seeing. 

Oh, are we supposed to cd to `/home/nginx/domains/sesdashboard.mysite.com/` before running git clone? So it would be `/home/nginx/domains/sesdashboard.mysite.com/sesdashboard/public` instead of `/home/nginx/domains/sesdashboard.mysite.com/public/sesdashboard/public`?

Or are we supposed to put all the contents of `sesdashboard` into `/home/nginx/domains/sesdashboard.mysite.com/` so that the `sesdashboard/public` folder is merged with the existing `public` folder? And then we delete the empty `/sesdashboard/` folder after moving all the contents?

Then we cd to `/home/nginx/domains/sesdashboard.mysite.com/public/sesdashboard/` before running `composer install` right?

**Comment by Nikeev** [comment]
Hello,

it seems that sesdashboard.mysite.com points to /home/nginx/domains/sesdashboard.mysite.com/public folder.
So you should unpack or git pull sesdashboard files this way:

`/home/nginx/domains/sesdashboard.mysite.com/public` (content of [sesdashboard/public/](https://github.com/Nikeev/sesdashboard/tree/master/public) folder)
`/home/nginx/domains/sesdashboard.mysite.com/scr` (content of [sesdashboard/src/](https://github.com/Nikeev/sesdashboard/tree/master/src) folder)
`/home/nginx/domains/sesdashboard.mysite.com/templates` (content of [sesdashboard/templates/](https://github.com/Nikeev/sesdashboard/tree/master/templates) folder)
... and so on.

So if you already have a public folder, you should replace its content with sesdashboard/public/

composer install you should run under `/home/nginx/domains/sesdashboard.mysite.com/`
`/home/nginx/domains/sesdashboard.mysite.com/ $ composer install`

**Comment by MaximilianKohler** [comment]
Ah, thank you. I was thinking that installing without docker would be lighter on system resources, but it seems that the non-docker install requires `php composer` which is resource intensive:

>https://centminmod.com/install.html
> 
>12. If you plan on using PHP [Composer](https://getcomposer.org/) for your web applications, you will want to have at least 3-4GB of memory on your server as Composer can use up to 1.5+ GB memory requirements itself and may require you raising the [PHP memory_limit up to 1.5GB or more](https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors)

So I'll just install docker and submit a PR to update the docs to note the Composer prerequisite.

**Comment by MaximilianKohler** [comment]
>So you should unpack or git pull sesdashboard files this way:

The git clone command automatically makes a `/home/nginx/domains/sesdashboard.mysite.com/sesdashboard/` directory instead of the correct `/home/nginx/domains/sesdashboard.mysite.com/` way, so maybe the git clone command in the docs should be altered?
